### ISSUE TITLE
Remove Woo logo and WooCommerce as a contributor 

### ISSUE THREAD

**Issue by darcie** [duckyname/notify-for-purchase#1]
Hi, I can't find another way to contact you. 

This plugin uses the Woo logo, which is trademarked. Without permission to use the logo, you may not include it in images. https://woocommerce.com/trademark-guidelines/

Can you please add a new logo that doesn't use our marks for both the plugin banner and icon? We have not granted permission for this use. 

It would be helpful to also add your own WordPress.org username in the Contributors and remove WooCommerce, as we didn't contribute to your code. 

Feel free to reach us at `partners@woocommerce.com` for any questions you'd like to ask privately. 

Thanks!

**Comment by duckyname** [comment]
Hello, I apologize for not being aware of the trademark requirements and the need for permission. I’ll update the logo and cover immediately and will reach out to you at partners@woocommerce.com. :)
